name: proto_schema_parser

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Build using Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3.10 -m venv venv
        source venv/bin/activate
        pip install pdm
        pdm install

    - name: Build ANTLR submodule
      run: |
        source venv/bin/activate
        pdm run antlr

    - name: Run black and isort
      run: |
        source venv/bin/activate
        pdm run isort --check --diff proto_schema_parser/ tests/
        pdm run black --check --diff proto_schema_parser/ tests/

    - name: Run pylint
      run: |
        source venv/bin/activate
        pdm run pylint proto_schema_parser/ tests/

    - name: Run pyright
      run: |
        source venv/bin/activate
        pdm run pyright

    - name: Test with pytest
      run: |
        source venv/bin/activate
        pdm run pytest
